---
# This is an example Kubernetes Secret that can be created in the Kubernetes
# Namespace where Ceph-CSI is deployed. The contents of this Secret will be
# used to fetch credentials from Amazon STS and use it connect to the
# Amazon KMS.
apiVersion: v1
kind: Secret
metadata:
  name: ceph-csi-aws-credentials
stringData:
  awsRoleARN: "arn:aws:iam::111122223333:role/aws-sts-kms"
  awsCMKARN: "arn:aws:kms:us-west-2:111123:key/1234cd-12ab-34cd-56ef-123590ab"
  awsRegion: "us-west-2"
