---
apiVersion: v1
kind: Pod
metadata:
  name: csi-nfs-clone-demo-app
spec:
  containers:
    - name: web-server
      image: docker.io/library/nginx:latest
      volumeMounts:
        - name: mypvc
          mountPath: /var/lib/www
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: nfs-pvc-clone
        readOnly: false
