---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-restore
spec:
  storageClassName: csi-nfs-sc
  dataSource:
    name: nfs-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
